pipeline {
    agent any 

    stages {
        stage('Restore Packages') {
            steps{
                echo '---- Restore Packages ----'
                sh 'pwd'
                sh 'dotnet restore'
            }
        }
        // stage('Clean'){
        //     sh 'dotnet clean WebApiApplication.csproj --configuration Release'
        // }
        // stage('Build'){
        //     sh 'dotnet build WebApiApplication.csproj --configuration Release --no-restore'
        // }
        // stage('Publish'){
        //     sh 'dotnet publish WebApiApplication.csproj --configuration Release --no-restore'
        // }
    }
}